@XuongMay_BE_HostAddress = https://localhost:7287

GET {{XuongMay_BE_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{XuongMay_BE_HostAddress}}/api/category

###

GET {{XuongMay_BE_HostAddress}}/api/category/0

###
